"""Add multi-tour booking support

Revision ID: e4c7a1149087
Revises: 38204ba4c342
Create Date: 2025-08-03 03:53:06.318700+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c7a1149087'
down_revision: Union[str, None] = '38204ba4c342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_tour_id_fkey', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'tour_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bookings_tour_id_fkey', 'bookings', 'tours', ['tour_id'], ['id'])
    # ### end Alembic commands ###
